// Branchenkatalog. Jede Branche wird über OpenStreetMap-Tags und/oder einen Namens-Regex gefunden.
// ma = typische Mitarbeiterzahl der Branche, dient nur als Basis für die grobe Schätzung.
const t = (k, v) => ({ k, v });

module.exports = [
  // ── Hochpreisige Produkte & Leistungen ──
  { id: 'kuechen', gruppe: 'hochpreis', label: 'Küchenstudios', ma: 8, tags: [t('shop', 'kitchen')], name: 'Küchenstudio|Küchenhaus|Einbauküchen' },
  { id: 'autohaus', gruppe: 'hochpreis', label: 'Autohäuser', ma: 25, tags: [t('shop', 'car')], name: 'Autohaus' },
  { id: 'wohnmobil', gruppe: 'hochpreis', label: 'Wohnmobile & Caravans', ma: 12, tags: [t('shop', 'caravan')], name: 'Wohnmobil|Caravan|Reisemobil' },
  { id: 'motorrad', gruppe: 'hochpreis', label: 'Motorradhändler', ma: 8, tags: [t('shop', 'motorcycle')] },
  { id: 'boote', gruppe: 'hochpreis', label: 'Boote & Yachten', ma: 8, tags: [t('shop', 'boat')], name: 'Bootsbau|Yachtservice|Bootswerft' },
  { id: 'moebel', gruppe: 'hochpreis', label: 'Möbel- & Einrichtungshäuser', ma: 15, tags: [t('shop', 'furniture'), t('shop', 'interior_decoration'), t('shop', 'bed')] },
  { id: 'juwelier', gruppe: 'hochpreis', label: 'Juweliere & Uhren', ma: 5, tags: [t('shop', 'jewelry'), t('shop', 'watches')] },
  { id: 'immobilien', gruppe: 'hochpreis', label: 'Immobilienmakler', ma: 6, tags: [t('office', 'estate_agent')] },
  { id: 'solar', gruppe: 'hochpreis', label: 'Solar & Photovoltaik', ma: 15, tags: [t('craft', 'photovoltaic'), t('craft', 'solar_energy')], name: 'Solar|Photovoltaik' },
  { id: 'fenster', gruppe: 'hochpreis', label: 'Fenster, Türen & Tore', ma: 12, tags: [t('craft', 'window_construction'), t('shop', 'doors'), t('shop', 'windows'), t('craft', 'glaziery')], name: 'Fensterbau|Fenster und Türen|Fenster & Türen|Torbau' },
  { id: 'wintergarten', gruppe: 'hochpreis', label: 'Wintergärten & Terrassendächer', ma: 10, tags: [], name: 'Wintergarten|Wintergärten|Terrassendach|Terrassendächer|Überdachung' },
  { id: 'shk', gruppe: 'hochpreis', label: 'Heizung, Sanitär & Bad', ma: 10, tags: [t('craft', 'plumber'), t('craft', 'hvac'), t('craft', 'heating_engineer'), t('shop', 'bathroom_furnishing')], name: 'Heizungsbau|Sanitär|Wärmepumpe|Badstudio' },
  { id: 'kamin', gruppe: 'hochpreis', label: 'Kamine & Öfen', ma: 6, tags: [t('shop', 'fireplace'), t('craft', 'stove_fitter')], name: 'Kaminbau|Kaminstudio|Ofenbau|Kachelofen' },
  { id: 'pool', gruppe: 'hochpreis', label: 'Pool, Sauna & Wellness', ma: 8, tags: [t('shop', 'swimming_pool')], name: 'Poolbau|Schwimmbadbau|Schwimmbadtechnik|Saunabau|Whirlpool' },
  { id: 'galabau', gruppe: 'hochpreis', label: 'Garten- & Landschaftsbau', ma: 12, tags: [t('craft', 'gardener'), t('craft', 'landscaper')], name: 'Garten- und Landschaftsbau|Galabau|GaLaBau|Gartengestaltung' },
  { id: 'bau', gruppe: 'hochpreis', label: 'Bauunternehmen & Hausbau', ma: 25, tags: [t('craft', 'builder'), t('office', 'construction_company'), t('craft', 'construction')], name: 'Bauunternehmen|Bauunternehmung|Massivhaus|Fertighaus|Hausbau|Bauträger' },
  { id: 'dach', gruppe: 'hochpreis', label: 'Dachdecker & Zimmereien', ma: 12, tags: [t('craft', 'roofer'), t('craft', 'carpenter')], name: 'Dachdecker|Bedachung|Zimmerei|Holzbau' },
  { id: 'schreiner', gruppe: 'hochpreis', label: 'Schreiner & Tischler', ma: 8, tags: [t('craft', 'joiner'), t('craft', 'cabinet_maker')], name: 'Schreinerei|Tischlerei|Möbelwerkstatt|Innenausbau' },
  { id: 'elektro', gruppe: 'hochpreis', label: 'Elektroinstallation & Gebäudetechnik', ma: 12, tags: [t('craft', 'electrician')], name: 'Elektrotechnik|Elektroinstallation|Gebäudetechnik' },
  { id: 'metallbau', gruppe: 'hochpreis', label: 'Metall- & Treppenbau', ma: 15, tags: [t('craft', 'metal_construction'), t('craft', 'blacksmith')], name: 'Metallbau|Stahlbau|Treppenbau|Schlosserei' },
  { id: 'boden', gruppe: 'hochpreis', label: 'Bodenbeläge & Parkett', ma: 8, tags: [t('shop', 'flooring'), t('craft', 'floorer'), t('craft', 'parquet_layer')], name: 'Parkett|Bodenbeläge' },
  { id: 'zahnarzt', gruppe: 'hochpreis', label: 'Zahnärzte & Kieferorthopäden', ma: 10, tags: [t('amenity', 'dentist'), t('healthcare', 'dentist')] },
  { id: 'aesthetik', gruppe: 'hochpreis', label: 'Ästhetik & Privatkliniken', ma: 12, tags: [t('healthcare:speciality', 'plastic_surgery')], name: 'Ästhetik|Schönheitsklinik|Privatklinik|Plastische Chirurgie|Haartransplantation' },
  { id: 'hoerakustik', gruppe: 'hochpreis', label: 'Hörakustiker', ma: 5, tags: [t('shop', 'hearing_aids')] },
  { id: 'optiker', gruppe: 'hochpreis', label: 'Optiker', ma: 6, tags: [t('shop', 'optician')] },
  { id: 'ebike', gruppe: 'hochpreis', label: 'Fahrrad- & E-Bike-Händler', ma: 8, tags: [t('shop', 'bicycle')] },
  { id: 'architekt', gruppe: 'hochpreis', label: 'Architekten & Ingenieurbüros', ma: 8, tags: [t('office', 'architect'), t('office', 'engineer')] },
  { id: 'finanz', gruppe: 'hochpreis', label: 'Finanz- & Versicherungsberater', ma: 5, tags: [t('office', 'insurance'), t('office', 'financial_advisor'), t('office', 'financial')] },
  { id: 'landtechnik', gruppe: 'hochpreis', label: 'Land- & Baumaschinen', ma: 20, tags: [t('shop', 'agrarian'), t('shop', 'tractor')], name: 'Landtechnik|Landmaschinen|Baumaschinen' },

  // ── Branchen mit hohem Personalbedarf ──
  { id: 'physio', gruppe: 'personal', label: 'Physiotherapie', ma: 7, tags: [t('healthcare', 'physiotherapist')], name: 'Physiotherapie|Krankengymnastik' },
  { id: 'ergo', gruppe: 'personal', label: 'Ergotherapie', ma: 6, tags: [t('healthcare', 'occupational_therapist')], name: 'Ergotherapie' },
  { id: 'logo', gruppe: 'personal', label: 'Logopädie', ma: 5, tags: [t('healthcare', 'speech_therapist')], name: 'Logopädie|Sprachtherapie' },
  { id: 'pflege', gruppe: 'personal', label: 'Pflegedienste & Pflegeheime', ma: 45, tags: [t('amenity', 'nursing_home'), t('social_facility', 'nursing_home'), t('social_facility', 'assisted_living'), t('social_facility', 'ambulatory_care'), t('healthcare', 'nursing'), t('healthcare', 'nurse')], name: 'Pflegedienst|Seniorenresidenz|Tagespflege|Intensivpflege' },
  { id: 'arzt', gruppe: 'personal', label: 'Arztpraxen & MVZ', ma: 7, tags: [t('amenity', 'doctors'), t('healthcare', 'doctor'), t('amenity', 'clinic'), t('healthcare', 'clinic')] },
  { id: 'tierarzt', gruppe: 'personal', label: 'Tierärzte', ma: 8, tags: [t('amenity', 'veterinary')] },
  { id: 'apotheke', gruppe: 'personal', label: 'Apotheken', ma: 10, tags: [t('amenity', 'pharmacy')] },
  { id: 'sanitaetshaus', gruppe: 'personal', label: 'Sanitätshäuser & Orthopädietechnik', ma: 12, tags: [t('shop', 'medical_supply'), t('craft', 'orthopaedics')], name: 'Sanitätshaus|Orthopädietechnik' },
  { id: 'kita', gruppe: 'personal', label: 'Kitas (private Träger)', ma: 15, tags: [t('amenity', 'kindergarten'), t('amenity', 'childcare')] },
  { id: 'gastro', gruppe: 'personal', label: 'Restaurants & Gastronomie', ma: 10, tags: [t('amenity', 'restaurant')] },
  { id: 'hotel', gruppe: 'personal', label: 'Hotels', ma: 25, tags: [t('tourism', 'hotel')] },
  { id: 'baeckerei', gruppe: 'personal', label: 'Bäckereien & Konditoreien', ma: 20, tags: [t('shop', 'bakery'), t('shop', 'pastry'), t('craft', 'bakery')] },
  { id: 'metzgerei', gruppe: 'personal', label: 'Metzgereien', ma: 12, tags: [t('shop', 'butcher')] },
  { id: 'friseur', gruppe: 'personal', label: 'Friseure', ma: 5, tags: [t('shop', 'hairdresser')] },
  { id: 'kosmetik', gruppe: 'personal', label: 'Kosmetik- & Beautystudios', ma: 4, tags: [t('shop', 'beauty')] },
  { id: 'kfz', gruppe: 'personal', label: 'Kfz-Werkstätten', ma: 8, tags: [t('shop', 'car_repair')] },
  { id: 'spedition', gruppe: 'personal', label: 'Speditionen & Logistik', ma: 40, tags: [t('office', 'logistics'), t('office', 'forwarder'), t('office', 'moving_company')], name: 'Spedition|Logistik|Transporte|Umzüge' },
  { id: 'reinigung', gruppe: 'personal', label: 'Gebäudereinigung', ma: 40, tags: [t('craft', 'cleaning'), t('office', 'cleaning')], name: 'Gebäudereinigung|Gebäudeservice|Gebäudedienste' },
  { id: 'sicherheit', gruppe: 'personal', label: 'Sicherheitsdienste', ma: 40, tags: [t('office', 'security')], name: 'Sicherheitsdienst|Wachschutz|Security' },
  { id: 'maler', gruppe: 'personal', label: 'Maler & Stuckateure', ma: 8, tags: [t('craft', 'painter'), t('craft', 'plasterer')], name: 'Malerbetrieb|Malermeister|Stuckateur' },
  { id: 'fliesen', gruppe: 'personal', label: 'Fliesenleger', ma: 6, tags: [t('craft', 'tiler')], name: 'Fliesenleger|Fliesenfachbetrieb' },
  { id: 'industrie', gruppe: 'personal', label: 'Industrie & Produktion', ma: 80, tags: [t('man_made', 'works'), t('office', 'company')], name: 'Maschinenbau|Anlagenbau|Werkzeugbau|Kunststofftechnik|Zerspanung' },
  { id: 'it', gruppe: 'personal', label: 'IT & Software', ma: 15, tags: [t('office', 'it'), t('office', 'software')], name: 'Software|IT-Service|Systemhaus' },
  { id: 'steuer', gruppe: 'personal', label: 'Steuerberater', ma: 10, tags: [t('office', 'tax_advisor'), t('office', 'accountant')] },
  { id: 'recht', gruppe: 'personal', label: 'Rechtsanwälte & Notare', ma: 8, tags: [t('office', 'lawyer'), t('office', 'notary')] },
  { id: 'fitness', gruppe: 'personal', label: 'Fitnessstudios', ma: 12, tags: [t('leisure', 'fitness_centre')] },
  { id: 'fahrschule', gruppe: 'personal', label: 'Fahrschulen', ma: 6, tags: [t('amenity', 'driving_school')] },
];
